name: Zola on GitHub Pages

on: 
 push:
  branches:
   - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main + submodules
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup mdbook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.23'
    - uses: jaxxstorm/action-install-gh-release@v1
      with:
        repo: badboy/mdbook-mermaid
        tag: v0.12.6
    - name: Build zola
      uses: shalzz/zola-deploy-action@v0.17.2
      env:
        BUILD_ONLY: true
    - name: Build mdbook
      run: mdbook build frc-programming
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
